#!/usr/bin/env bash
# This script handles SIGTERM with a custom message and runs indefinitely

trap 'echo "I am invincible!!!"' TERM

while true
do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
