#!/usr/bin/env bash
# Script that runs infinitely and handles SIGTERM by printing a message instead of exiting

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
